name = "lotrme-github-posts"
type = "javascript"
account_id = "18e4505e0d7087e09ca39b1128f2cd7e"
workers_dev = true

compatibility_date = "2025-03-19"

# module format is required to have fetch() as well as scheduled()
[build]
upload.format = "modules"
upload.main = "./src/index.js"

# cron trigger for running every day
[triggers]
crons = ["0 0 * * *"]

[observability.logs]
enabled = true
