name = "lotrme-github-posts"
type = "javascript"
account_id = "18e4505e0d7087e09ca39b1128f2cd7e"
workers_dev = true

# Entry point
main = "src/index.js"

# last changed
compatibility_date = "2025-02-25"

# Webhook links
[vars]
SUGGESTIONS_WEBHOOK = "" 
NEWS_WEBHOOK = ""
CHANGELOG_WEBHOOK = ""
